data = [
  ["item","expt","condition","group","order","pic_width","pic_height","place_target","Colour_Thing","Number","PicFilename","sentence","Sound_filename","language","determiner"  ],
  ["37","practice","B","1","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","CT"  ],
  ["37","practice","B","4","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","CT"  ],
  ["37","practice","B","7","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","CT"  ],
  ["38","practice","C","1","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","CT"  ],
  ["38","practice","C","4","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","CT"  ],
  ["38","practice","C","7","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","CT"  ],
  ["1","picture","A","1","2","400","400","top-left","Green_Socks","One","1_One_Green_Socks.PNG","Mary has green socks. ","1_DE_CT.wav","DE","CT"  ],
  ["1","picture","B","4","2","400","400","top-left","Green_Socks","Two","1_Two_Green_Socks.PNG","Mary has green socks. ","1_DE_CT.wav","DE","CT"  ],
  ["1","picture","C","7","2","400","400","top-left","Green_Socks","Three","1_Three_Green_Socks.PNG","Mary has green socks. ","1_DE_CT.wav","DE","CT"  ],
  ["2","picture","A","4","2","400","400","top-right","Green_Tshirts","One","2_One_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_CT.wav","DE","CT"  ],
  ["2","picture","B","7","2","400","400","top-right","Green_Tshirts","Two","2_Two_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_CT.wav","DE","CT"  ],
  ["2","picture","C","1","2","400","400","top-right","Green_Tshirts","Three","2_Three_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_CT.wav","DE","CT"  ],
  ["3","picture","A","7","2","400","400","bottom-left","Red_Armchairs","One","3_One_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_CT.wav","DE","CT"  ],
  ["3","picture","B","1","2","400","400","bottom-left","Red_Armchairs","Two","3_Two_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_CT.wav","DE","CT"  ],
  ["3","picture","C","4","2","400","400","bottom-left","Red_Armchairs","Three","3_Three_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_CT.wav","DE","CT"  ],
  ["4","picture","A","1","2","400","400","bottom-left","Brown_Horses","One","4_One_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_CT.wav","DE","CT"  ],
  ["4","picture","B","4","2","400","400","bottom-left","Brown_Horses","Two","4_Two_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_CT.wav","DE","CT"  ],
  ["4","picture","C","7","2","400","400","bottom-left","Brown_Horses","Three","4_Three_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_CT.wav","DE","CT"  ],
  ["5","picture","A","4","2","400","400","top-left","Green_Cars","One","5_One_Green_Cars.PNG","Karla has a green car. ","5_DE_CT.wav","DE","CT"  ],
  ["5","picture","B","7","2","400","400","top-left","Green_Cars","Two","5_Two_Green_Cars.PNG","Karla has a green car. ","5_DE_CT.wav","DE","CT"  ],
  ["5","picture","C","1","2","400","400","top-left","Green_Cars","Three","5_Three_Green_Cars.PNG","Karla has a green car. ","5_DE_CT.wav","DE","CT"  ],
  ["6","picture","A","7","2","400","400","bottom-left","Black_Trousers","One","6_One_Black_Trousers.PNG","Marco has black trousers. ","6_DE_CT.wav","DE","CT"  ],
  ["6","picture","B","1","2","400","400","bottom-left","Black_Trousers","Two","6_Two_Black_Trousers.PNG","Marco has black trousers. ","6_DE_CT.wav","DE","CT"  ],
  ["6","picture","C","4","2","400","400","bottom-left","Black_Trousers","Three","6_Three_Black_Trousers.PNG","Marco has black trousers. ","6_DE_CT.wav","DE","CT"  ],
  ["7","picture","A","1","2","400","400","bottom-right","Red_Hats","One","7_One_Red_Hats.PNG","Silvia has a red hat. ","7_DE_CT.wav","DE","CT"  ],
  ["7","picture","B","4","2","400","400","bottom-right","Red_Hats","Two","7_Two_Red_Hats.PNG","Silvia has a red hat. ","7_DE_CT.wav","DE","CT"  ],
  ["7","picture","C","7","2","400","400","bottom-right","Red_Hats","Three","7_Three_Red_Hats.PNG","Silvia has a red hat. ","7_DE_CT.wav","DE","CT"  ],
  ["8","picture","A","4","2","400","400","top-left","Red_Balls","One","8_One_Red_Balls.PNG","Lukas has a red ball. ","8_DE_CT.wav","DE","CT"  ],
  ["8","picture","B","7","2","400","400","top-left","Red_Balls","Two","8_Two_Red_Balls.PNG","Lukas has a red ball. ","8_DE_CT.wav","DE","CT"  ],
  ["8","picture","C","1","2","400","400","top-left","Red_Balls","Three","8_Three_Red_Balls.PNG","Lukas has a red ball. ","8_DE_CT.wav","DE","CT"  ],
  ["9","picture","A","7","2","400","400","top-right","Blue_Houses","One","9_One_Blue_Houses.PNG","Simon has a blue house. ","9_DE_CT.wav","DE","CT"  ],
  ["9","picture","B","1","2","400","400","top-right","Blue_Houses","Two","9_Two_Blue_Houses.PNG","Simon has a blue house. ","9_DE_CT.wav","DE","CT"  ],
  ["9","picture","C","4","2","400","400","top-right","Blue_Houses","Three","9_Three_Blue_Houses.PNG","Simon has a blue house. ","9_DE_CT.wav","DE","CT"  ],
  ["10","picture","A","1","2","400","400","bottom-left","Green_Buckets","One","10_One_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_CT.wav","DE","CT"  ],
  ["10","picture","B","4","2","400","400","bottom-left","Green_Buckets","Two","10_Two_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_CT.wav","DE","CT"  ],
  ["10","picture","C","7","2","400","400","bottom-left","Green_Buckets","Three","10_Three_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_CT.wav","DE","CT"  ],
  ["11","picture","A","4","2","400","400","bottom-left","Blue_Teddies","One","11_One_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_CT.wav","DE","CT"  ],
  ["11","picture","B","7","2","400","400","bottom-left","Blue_Teddies","Two","11_Two_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_CT.wav","DE","CT"  ],
  ["11","picture","C","1","2","400","400","bottom-left","Blue_Teddies","Three","11_Three_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_CT.wav","DE","CT"  ],
  ["12","picture","A","7","2","400","400","bottom-left","Blue_Boats","One","12_One_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_CT.wav","DE","CT"  ],
  ["12","picture","B","1","2","400","400","bottom-left","Blue_Boats","Two","12_Two_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_CT.wav","DE","CT"  ],
  ["12","picture","C","4","2","400","400","bottom-left","Blue_Boats","Three","12_Three_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_CT.wav","DE","CT"  ],
  ["13","picture","A","1","2","400","400","top-left","Blue_Scarfs","One","13_One_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_CT.wav","DE","CT"  ],
  ["13","picture","B","4","2","400","400","top-left","Blue_Scarfs","Two","13_Two_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_CT.wav","DE","CT"  ],
  ["13","picture","C","7","2","400","400","top-left","Blue_Scarfs","Three","13_Three_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_CT.wav","DE","CT"  ],
  ["14","picture","A","4","2","400","400","bottom-left","Blue_Sofas","One","14_One_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_CT.wav","DE","CT"  ],
  ["14","picture","B","7","2","400","400","bottom-left","Blue_Sofas","Two","14_Two_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_CT.wav","DE","CT"  ],
  ["14","picture","C","1","2","400","400","bottom-left","Blue_Sofas","Three","14_Three_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_CT.wav","DE","CT"  ],
  ["15","picture","A","7","2","400","400","bottom-right","Blue_Lamps","One","15_One_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_CT.wav","DE","CT"  ],
  ["15","picture","B","1","2","400","400","bottom-right","Blue_Lamps","Two","15_Two_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_CT.wav","DE","CT"  ],
  ["15","picture","C","4","2","400","400","bottom-right","Blue_Lamps","Three","15_Three_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_CT.wav","DE","CT"  ],
  ["16","picture","A","1","2","400","400","top-left","Red_Jackets","One","16_One_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_CT.wav","DE","CT"  ],
  ["16","picture","B","4","2","400","400","top-left","Red_Jackets","Two","16_Two_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_CT.wav","DE","CT"  ],
  ["16","picture","C","7","2","400","400","top-left","Red_Jackets","Three","16_Three_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_CT.wav","DE","CT"  ],
  ["17","picture","A","4","2","400","400","top-left","Blue_Shoes","One","17_One_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_CT.wav","DE","CT"  ],
  ["17","picture","B","7","2","400","400","top-left","Blue_Shoes","Two","17_Two_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_CT.wav","DE","CT"  ],
  ["17","picture","C","1","2","400","400","top-left","Blue_Shoes","Three","17_Three_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_CT.wav","DE","CT"  ],
  ["18","picture","A","7","2","400","400","bottom-left","Green_Tents","One","18_One_Green_Tents.PNG","Julian has a green tent. ","18_DE_CT.wav","DE","CT"  ],
  ["18","picture","B","1","2","400","400","bottom-left","Green_Tents","Two","18_Two_Green_Tents.PNG","Julian has a green tent. ","18_DE_CT.wav","DE","CT"  ],
  ["18","picture","C","4","2","400","400","bottom-left","Green_Tents","Three","18_Three_Green_Tents.PNG","Julian has a green tent. ","18_DE_CT.wav","DE","CT"  ],
  ["19","filler","A","1","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","CT"  ],
  ["19","filler","A","4","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","CT"  ],
  ["19","filler","A","7","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","CT"  ],
  ["20","filler","A","4","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","CT"  ],
  ["20","filler","A","7","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","CT"  ],
  ["20","filler","A","1","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","CT"  ],
  ["21","filler","A","7","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","CT"  ],
  ["21","filler","A","1","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","CT"  ],
  ["21","filler","A","4","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","CT"  ],
  ["22","filler","A","1","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","CT"  ],
  ["22","filler","A","4","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","CT"  ],
  ["22","filler","A","7","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","CT"  ],
  ["23","filler","A","4","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","CT"  ],
  ["23","filler","A","7","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","CT"  ],
  ["23","filler","A","1","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","CT"  ],
  ["24","filler","A","7","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","CT"  ],
  ["24","filler","A","1","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","CT"  ],
  ["24","filler","A","4","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","CT"  ],
  ["25","filler","B","1","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","CT"  ],
  ["25","filler","B","4","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","CT"  ],
  ["25","filler","B","7","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","CT"  ],
  ["26","filler","B","4","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","CT"  ],
  ["26","filler","B","7","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","CT"  ],
  ["26","filler","B","1","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","CT"  ],
  ["27","filler","B","7","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","CT"  ],
  ["27","filler","B","1","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","CT"  ],
  ["27","filler","B","4","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","CT"  ],
  ["28","filler","B","1","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","CT"  ],
  ["28","filler","B","4","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","CT"  ],
  ["28","filler","B","7","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","CT"  ],
  ["29","filler","B","4","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","CT"  ],
  ["29","filler","B","7","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","CT"  ],
  ["29","filler","B","1","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","CT"  ],
  ["30","filler","B","7","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","CT"  ],
  ["30","filler","C","1","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","CT"  ],
  ["30","filler","C","4","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","CT"  ],
  ["31","filler","C","1","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","CT"  ],
  ["31","filler","C","4","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","CT"  ],
  ["31","filler","C","7","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","CT"  ],
  ["32","filler","C","4","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","CT"  ],
  ["32","filler","C","7","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","CT"  ],
  ["32","filler","C","1","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","CT"  ],
  ["33","filler","C","7","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","CT"  ],
  ["33","filler","C","1","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","CT"  ],
  ["33","filler","C","4","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","CT"  ],
  ["34","filler","C","1","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","CT"  ],
  ["34","filler","C","4","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","CT"  ],
  ["34","filler","C","7","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","CT"  ],
  ["35","filler","C","4","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","CT"  ],
  ["35","filler","C","7","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","CT"  ],
  ["35","filler","C","1","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","CT"  ],
  ["36","filler","C","7","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","CT"  ],
  ["36","filler","C","1","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","CT"  ],
  ["36","filler","C","4","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","CT"  ],
  ["37","practice","B","2","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","F"  ],
  ["37","practice","B","5","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","F"  ],
  ["37","practice","B","8","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","F"  ],
  ["38","practice","C","2","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","F"  ],
  ["38","practice","C","5","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","F"  ],
  ["38","practice","C","8","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","F"  ],
  ["1","picture","A","2","2","400","400","top-left","Green_Socks","One","1_One_Green_Socks.PNG","Mary has green socks. ","1_DE_F.wav","DE","F"  ],
  ["1","picture","B","5","2","400","400","top-left","Green_Socks","Two","1_Two_Green_Socks.PNG","Mary has green socks. ","1_DE_F.wav","DE","F"  ],
  ["1","picture","C","8","2","400","400","top-left","Green_Socks","Three","1_Three_Green_Socks.PNG","Mary has green socks. ","1_DE_F.wav","DE","F"  ],
  ["2","picture","A","5","2","400","400","top-right","Green_Tshirts","One","2_One_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_F.wav","DE","F"  ],
  ["2","picture","B","8","2","400","400","top-right","Green_Tshirts","Two","2_Two_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_F.wav","DE","F"  ],
  ["2","picture","C","2","2","400","400","top-right","Green_Tshirts","Three","2_Three_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_F.wav","DE","F"  ],
  ["3","picture","A","8","2","400","400","bottom-left","Red_Armchairs","One","3_One_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_F.wav","DE","F"  ],
  ["3","picture","B","2","2","400","400","bottom-left","Red_Armchairs","Two","3_Two_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_F.wav","DE","F"  ],
  ["3","picture","C","5","2","400","400","bottom-left","Red_Armchairs","Three","3_Three_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_F.wav","DE","F"  ],
  ["4","picture","A","2","2","400","400","bottom-left","Brown_Horses","One","4_One_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_F.wav","DE","F"  ],
  ["4","picture","B","5","2","400","400","bottom-left","Brown_Horses","Two","4_Two_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_F.wav","DE","F"  ],
  ["4","picture","C","8","2","400","400","bottom-left","Brown_Horses","Three","4_Three_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_F.wav","DE","F"  ],
  ["5","picture","A","5","2","400","400","top-left","Green_Cars","One","5_One_Green_Cars.PNG","Karla has a green car. ","5_DE_F.wav","DE","F"  ],
  ["5","picture","B","8","2","400","400","top-left","Green_Cars","Two","5_Two_Green_Cars.PNG","Karla has a green car. ","5_DE_F.wav","DE","F"  ],
  ["5","picture","C","2","2","400","400","top-left","Green_Cars","Three","5_Three_Green_Cars.PNG","Karla has a green car. ","5_DE_F.wav","DE","F"  ],
  ["6","picture","A","8","2","400","400","bottom-left","Black_Trousers","One","6_One_Black_Trousers.PNG","Marco has black trousers. ","6_DE_F.wav","DE","F"  ],
  ["6","picture","B","2","2","400","400","bottom-left","Black_Trousers","Two","6_Two_Black_Trousers.PNG","Marco has black trousers. ","6_DE_F.wav","DE","F"  ],
  ["6","picture","C","5","2","400","400","bottom-left","Black_Trousers","Three","6_Three_Black_Trousers.PNG","Marco has black trousers. ","6_DE_F.wav","DE","F"  ],
  ["7","picture","A","2","2","400","400","bottom-right","Red_Hats","One","7_One_Red_Hats.PNG","Silvia has a red hat. ","7_DE_F.wav","DE","F"  ],
  ["7","picture","B","5","2","400","400","bottom-right","Red_Hats","Two","7_Two_Red_Hats.PNG","Silvia has a red hat. ","7_DE_F.wav","DE","F"  ],
  ["7","picture","C","8","2","400","400","bottom-right","Red_Hats","Three","7_Three_Red_Hats.PNG","Silvia has a red hat. ","7_DE_F.wav","DE","F"  ],
  ["8","picture","A","5","2","400","400","top-left","Red_Balls","One","8_One_Red_Balls.PNG","Lukas has a red ball. ","8_DE_F.wav","DE","F"  ],
  ["8","picture","B","8","2","400","400","top-left","Red_Balls","Two","8_Two_Red_Balls.PNG","Lukas has a red ball. ","8_DE_F.wav","DE","F"  ],
  ["8","picture","C","2","2","400","400","top-left","Red_Balls","Three","8_Three_Red_Balls.PNG","Lukas has a red ball. ","8_DE_F.wav","DE","F"  ],
  ["9","picture","A","8","2","400","400","top-right","Blue_Houses","One","9_One_Blue_Houses.PNG","Simon has a blue house. ","9_DE_F.wav","DE","F"  ],
  ["9","picture","B","2","2","400","400","top-right","Blue_Houses","Two","9_Two_Blue_Houses.PNG","Simon has a blue house. ","9_DE_F.wav","DE","F"  ],
  ["9","picture","C","5","2","400","400","top-right","Blue_Houses","Three","9_Three_Blue_Houses.PNG","Simon has a blue house. ","9_DE_F.wav","DE","F"  ],
  ["10","picture","A","2","2","400","400","bottom-left","Green_Buckets","One","10_One_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_F.wav","DE","F"  ],
  ["10","picture","B","5","2","400","400","bottom-left","Green_Buckets","Two","10_Two_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_F.wav","DE","F"  ],
  ["10","picture","C","8","2","400","400","bottom-left","Green_Buckets","Three","10_Three_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_F.wav","DE","F"  ],
  ["11","picture","A","5","2","400","400","bottom-left","Blue_Teddies","One","11_One_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_F.wav","DE","F"  ],
  ["11","picture","B","8","2","400","400","bottom-left","Blue_Teddies","Two","11_Two_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_F.wav","DE","F"  ],
  ["11","picture","C","2","2","400","400","bottom-left","Blue_Teddies","Three","11_Three_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_F.wav","DE","F"  ],
  ["12","picture","A","8","2","400","400","bottom-left","Blue_Boats","One","12_One_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_F.wav","DE","F"  ],
  ["12","picture","B","2","2","400","400","bottom-left","Blue_Boats","Two","12_Two_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_F.wav","DE","F"  ],
  ["12","picture","C","5","2","400","400","bottom-left","Blue_Boats","Three","12_Three_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_F.wav","DE","F"  ],
  ["13","picture","A","2","2","400","400","top-left","Blue_Scarfs","One","13_One_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_F.wav","DE","F"  ],
  ["13","picture","B","5","2","400","400","top-left","Blue_Scarfs","Two","13_Two_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_F.wav","DE","F"  ],
  ["13","picture","C","8","2","400","400","top-left","Blue_Scarfs","Three","13_Three_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_F.wav","DE","F"  ],
  ["14","picture","A","5","2","400","400","bottom-left","Blue_Sofas","One","14_One_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_F.wav","DE","F"  ],
  ["14","picture","B","8","2","400","400","bottom-left","Blue_Sofas","Two","14_Two_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_F.wav","DE","F"  ],
  ["14","picture","C","2","2","400","400","bottom-left","Blue_Sofas","Three","14_Three_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_F.wav","DE","F"  ],
  ["15","picture","A","8","2","400","400","bottom-right","Blue_Lamps","One","15_One_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_F.wav","DE","F"  ],
  ["15","picture","B","2","2","400","400","bottom-right","Blue_Lamps","Two","15_Two_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_F.wav","DE","F"  ],
  ["15","picture","C","5","2","400","400","bottom-right","Blue_Lamps","Three","15_Three_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_F.wav","DE","F"  ],
  ["16","picture","A","2","2","400","400","top-left","Red_Jackets","One","16_One_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_F.wav","DE","F"  ],
  ["16","picture","B","5","2","400","400","top-left","Red_Jackets","Two","16_Two_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_F.wav","DE","F"  ],
  ["16","picture","C","8","2","400","400","top-left","Red_Jackets","Three","16_Three_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_F.wav","DE","F"  ],
  ["17","picture","A","5","2","400","400","top-left","Blue_Shoes","One","17_One_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_F.wav","DE","F"  ],
  ["17","picture","B","8","2","400","400","top-left","Blue_Shoes","Two","17_Two_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_F.wav","DE","F"  ],
  ["17","picture","C","2","2","400","400","top-left","Blue_Shoes","Three","17_Three_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_F.wav","DE","F"  ],
  ["18","picture","A","8","2","400","400","bottom-left","Green_Tents","One","18_One_Green_Tents.PNG","Julian has a green tent. ","18_DE_F.wav","DE","F"  ],
  ["18","picture","B","2","2","400","400","bottom-left","Green_Tents","Two","18_Two_Green_Tents.PNG","Julian has a green tent. ","18_DE_F.wav","DE","F"  ],
  ["18","picture","C","5","2","400","400","bottom-left","Green_Tents","Three","18_Three_Green_Tents.PNG","Julian has a green tent. ","18_DE_F.wav","DE","F"  ],
  ["19","filler","A","2","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","F"  ],
  ["19","filler","A","5","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","F"  ],
  ["19","filler","A","8","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","F"  ],
  ["20","filler","A","5","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","F"  ],
  ["20","filler","A","8","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","F"  ],
  ["20","filler","A","2","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","F"  ],
  ["21","filler","A","8","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","F"  ],
  ["21","filler","A","2","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","F"  ],
  ["21","filler","A","5","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","F"  ],
  ["22","filler","A","2","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","F"  ],
  ["22","filler","A","5","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","F"  ],
  ["22","filler","A","8","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","F"  ],
  ["23","filler","A","5","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","F"  ],
  ["23","filler","A","8","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","F"  ],
  ["23","filler","A","2","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","F"  ],
  ["24","filler","A","8","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","F"  ],
  ["24","filler","A","2","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","F"  ],
  ["24","filler","A","5","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","F"  ],
  ["25","filler","B","2","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","F"  ],
  ["25","filler","B","5","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","F"  ],
  ["25","filler","B","8","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","F"  ],
  ["26","filler","B","5","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","F"  ],
  ["26","filler","B","8","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","F"  ],
  ["26","filler","B","2","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","F"  ],
  ["27","filler","B","8","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","F"  ],
  ["27","filler","B","2","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","F"  ],
  ["27","filler","B","5","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","F"  ],
  ["28","filler","B","2","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","F"  ],
  ["28","filler","B","5","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","F"  ],
  ["28","filler","B","8","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","F"  ],
  ["29","filler","B","5","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","F"  ],
  ["29","filler","B","8","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","F"  ],
  ["29","filler","B","2","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","F"  ],
  ["30","filler","B","8","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","F"  ],
  ["30","filler","C","2","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","F"  ],
  ["30","filler","C","5","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","F"  ],
  ["31","filler","C","2","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","F"  ],
  ["31","filler","C","5","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","F"  ],
  ["31","filler","C","8","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","F"  ],
  ["32","filler","C","5","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","F"  ],
  ["32","filler","C","8","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","F"  ],
  ["32","filler","C","2","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","F"  ],
  ["33","filler","C","8","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","F"  ],
  ["33","filler","C","2","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","F"  ],
  ["33","filler","C","5","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","F"  ],
  ["34","filler","C","2","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","F"  ],
  ["34","filler","C","5","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","F"  ],
  ["34","filler","C","8","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","F"  ],
  ["35","filler","C","5","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","F"  ],
  ["35","filler","C","8","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","F"  ],
  ["35","filler","C","2","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","F"  ],
  ["36","filler","C","8","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","F"  ],
  ["36","filler","C","2","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","F"  ],
  ["36","filler","C","5","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","F"  ],
  ["37","practice","B","3","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","Cleft"  ],
  ["37","practice","B","6","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","Cleft"  ],
  ["37","practice","B","9","1","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","Cleft"  ],
  ["38","practice","C","3","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","Cleft"  ],
  ["38","practice","C","6","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","Cleft"  ],
  ["38","practice","C","9","1","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","Cleft"  ],
  ["1","picture","A","3","2","400","400","top-left","Green_Socks","One","1_One_Green_Socks.PNG","Mary has green socks. ","1_DE_Cleft.wav","DE","Cleft"  ],
  ["1","picture","B","6","2","400","400","top-left","Green_Socks","Two","1_Two_Green_Socks.PNG","Mary has green socks. ","1_DE_Cleft.wav","DE","Cleft"  ],
  ["1","picture","C","9","2","400","400","top-left","Green_Socks","Three","1_Three_Green_Socks.PNG","Mary has green socks. ","1_DE_Cleft.wav","DE","Cleft"  ],
  ["2","picture","A","6","2","400","400","top-right","Green_Tshirts","One","2_One_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_Cleft.wav","DE","Cleft"  ],
  ["2","picture","B","9","2","400","400","top-right","Green_Tshirts","Two","2_Two_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_Cleft.wav","DE","Cleft"  ],
  ["2","picture","C","3","2","400","400","top-right","Green_Tshirts","Three","2_Three_Green_Tshirts.PNG","Maike has a green t-shirt. ","2_DE_Cleft.wav","DE","Cleft"  ],
  ["3","picture","A","9","2","400","400","bottom-left","Red_Armchairs","One","3_One_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_Cleft.wav","DE","Cleft"  ],
  ["3","picture","B","3","2","400","400","bottom-left","Red_Armchairs","Two","3_Two_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_Cleft.wav","DE","Cleft"  ],
  ["3","picture","C","6","2","400","400","bottom-left","Red_Armchairs","Three","3_Three_Red_Armchairs.PNG","Ben has a red armchair. ","3_DE_Cleft.wav","DE","Cleft"  ],
  ["4","picture","A","3","2","400","400","bottom-left","Brown_Horses","One","4_One_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_Cleft.wav","DE","Cleft"  ],
  ["4","picture","B","6","2","400","400","bottom-left","Brown_Horses","Two","4_Two_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_Cleft.wav","DE","Cleft"  ],
  ["4","picture","C","9","2","400","400","bottom-left","Brown_Horses","Three","4_Three_Brown_Horses.PNG","Jacob has a brown horse. ","4_DE_Cleft.wav","DE","Cleft"  ],
  ["5","picture","A","6","2","400","400","top-left","Green_Cars","One","5_One_Green_Cars.PNG","Karla has a green car. ","5_DE_Cleft.wav","DE","Cleft"  ],
  ["5","picture","B","9","2","400","400","top-left","Green_Cars","Two","5_Two_Green_Cars.PNG","Karla has a green car. ","5_DE_Cleft.wav","DE","Cleft"  ],
  ["5","picture","C","3","2","400","400","top-left","Green_Cars","Three","5_Three_Green_Cars.PNG","Karla has a green car. ","5_DE_Cleft.wav","DE","Cleft"  ],
  ["6","picture","A","9","2","400","400","bottom-left","Black_Trousers","One","6_One_Black_Trousers.PNG","Marco has black trousers. ","6_DE_Cleft.wav","DE","Cleft"  ],
  ["6","picture","B","3","2","400","400","bottom-left","Black_Trousers","Two","6_Two_Black_Trousers.PNG","Marco has black trousers. ","6_DE_Cleft.wav","DE","Cleft"  ],
  ["6","picture","C","6","2","400","400","bottom-left","Black_Trousers","Three","6_Three_Black_Trousers.PNG","Marco has black trousers. ","6_DE_Cleft.wav","DE","Cleft"  ],
  ["7","picture","A","3","2","400","400","bottom-right","Red_Hats","One","7_One_Red_Hats.PNG","Silvia has a red hat. ","7_DE_Cleft.wav","DE","Cleft"  ],
  ["7","picture","B","6","2","400","400","bottom-right","Red_Hats","Two","7_Two_Red_Hats.PNG","Silvia has a red hat. ","7_DE_Cleft.wav","DE","Cleft"  ],
  ["7","picture","C","9","2","400","400","bottom-right","Red_Hats","Three","7_Three_Red_Hats.PNG","Silvia has a red hat. ","7_DE_Cleft.wav","DE","Cleft"  ],
  ["8","picture","A","6","2","400","400","top-left","Red_Balls","One","8_One_Red_Balls.PNG","Lukas has a red ball. ","8_DE_Cleft.wav","DE","Cleft"  ],
  ["8","picture","B","9","2","400","400","top-left","Red_Balls","Two","8_Two_Red_Balls.PNG","Lukas has a red ball. ","8_DE_Cleft.wav","DE","Cleft"  ],
  ["8","picture","C","3","2","400","400","top-left","Red_Balls","Three","8_Three_Red_Balls.PNG","Lukas has a red ball. ","8_DE_Cleft.wav","DE","Cleft"  ],
  ["9","picture","A","9","2","400","400","top-right","Blue_Houses","One","9_One_Blue_Houses.PNG","Simon has a blue house. ","9_DE_Cleft.wav","DE","Cleft"  ],
  ["9","picture","B","3","2","400","400","top-right","Blue_Houses","Two","9_Two_Blue_Houses.PNG","Simon has a blue house. ","9_DE_Cleft.wav","DE","Cleft"  ],
  ["9","picture","C","6","2","400","400","top-right","Blue_Houses","Three","9_Three_Blue_Houses.PNG","Simon has a blue house. ","9_DE_Cleft.wav","DE","Cleft"  ],
  ["10","picture","A","3","2","400","400","bottom-left","Green_Buckets","One","10_One_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_Cleft.wav","DE","Cleft"  ],
  ["10","picture","B","6","2","400","400","bottom-left","Green_Buckets","Two","10_Two_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_Cleft.wav","DE","Cleft"  ],
  ["10","picture","C","9","2","400","400","bottom-left","Green_Buckets","Three","10_Three_Green_Buckets.PNG","Kai has a green bucket. ","10_DE_Cleft.wav","DE","Cleft"  ],
  ["11","picture","A","6","2","400","400","bottom-left","Blue_Teddies","One","11_One_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_Cleft.wav","DE","Cleft"  ],
  ["11","picture","B","9","2","400","400","bottom-left","Blue_Teddies","Two","11_Two_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_Cleft.wav","DE","Cleft"  ],
  ["11","picture","C","3","2","400","400","bottom-left","Blue_Teddies","Three","11_Three_Blue_Teddies.PNG","Markus has a blue teddy. ","11_DE_Cleft.wav","DE","Cleft"  ],
  ["12","picture","A","9","2","400","400","bottom-left","Blue_Boats","One","12_One_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_Cleft.wav","DE","Cleft"  ],
  ["12","picture","B","3","2","400","400","bottom-left","Blue_Boats","Two","12_Two_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_Cleft.wav","DE","Cleft"  ],
  ["12","picture","C","6","2","400","400","bottom-left","Blue_Boats","Three","12_Three_Blue_Boats.PNG","Konstantin has a blue boat. ","12_DE_Cleft.wav","DE","Cleft"  ],
  ["13","picture","A","3","2","400","400","top-left","Blue_Scarfs","One","13_One_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_Cleft.wav","DE","Cleft"  ],
  ["13","picture","B","6","2","400","400","top-left","Blue_Scarfs","Two","13_Two_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_Cleft.wav","DE","Cleft"  ],
  ["13","picture","C","9","2","400","400","top-left","Blue_Scarfs","Three","13_Three_Blue_Scarfs.PNG","Sandra has a blue scarf. ","13_DE_Cleft.wav","DE","Cleft"  ],
  ["14","picture","A","6","2","400","400","bottom-left","Blue_Sofas","One","14_One_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_Cleft.wav","DE","Cleft"  ],
  ["14","picture","B","9","2","400","400","bottom-left","Blue_Sofas","Two","14_Two_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_Cleft.wav","DE","Cleft"  ],
  ["14","picture","C","3","2","400","400","bottom-left","Blue_Sofas","Three","14_Three_Blue_Sofas.PNG","Annika has a blue sofa. ","14_DE_Cleft.wav","DE","Cleft"  ],
  ["15","picture","A","9","2","400","400","bottom-right","Blue_Lamps","One","15_One_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_Cleft.wav","DE","Cleft"  ],
  ["15","picture","B","3","2","400","400","bottom-right","Blue_Lamps","Two","15_Two_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_Cleft.wav","DE","Cleft"  ],
  ["15","picture","C","6","2","400","400","bottom-right","Blue_Lamps","Three","15_Three_Blue_Lamps.PNG","Brigitte has a blue lamp.","15_DE_Cleft.wav","DE","Cleft"  ],
  ["16","picture","A","3","2","400","400","top-left","Red_Jackets","One","16_One_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_Cleft.wav","DE","Cleft"  ],
  ["16","picture","B","6","2","400","400","top-left","Red_Jackets","Two","16_Two_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_Cleft.wav","DE","Cleft"  ],
  ["16","picture","C","9","2","400","400","top-left","Red_Jackets","Three","16_Three_Red_Jackets.PNG","Alex has a red jacket. ","16_DE_Cleft.wav","DE","Cleft"  ],
  ["17","picture","A","6","2","400","400","top-left","Blue_Shoes","One","17_One_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_Cleft.wav","DE","Cleft"  ],
  ["17","picture","B","9","2","400","400","top-left","Blue_Shoes","Two","17_Two_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_Cleft.wav","DE","Cleft"  ],
  ["17","picture","C","3","2","400","400","top-left","Blue_Shoes","Three","17_Three_Blue_Shoes.PNG","Sina has a blue shoe. ","17_DE_Cleft.wav","DE","Cleft"  ],
  ["18","picture","A","9","2","400","400","bottom-left","Green_Tents","One","18_One_Green_Tents.PNG","Julian has a green tent. ","18_DE_Cleft.wav","DE","Cleft"  ],
  ["18","picture","B","3","2","400","400","bottom-left","Green_Tents","Two","18_Two_Green_Tents.PNG","Julian has a green tent. ","18_DE_Cleft.wav","DE","Cleft"  ],
  ["18","picture","C","6","2","400","400","bottom-left","Green_Tents","Three","18_Three_Green_Tents.PNG","Julian has a green tent. ","18_DE_Cleft.wav","DE","Cleft"  ],
  ["19","filler","A","3","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","Cleft"  ],
  ["19","filler","A","6","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","Cleft"  ],
  ["19","filler","A","9","2","400","400","top-right","","","19_Only_False.PNG","Only Karl has a football. ","19_DE.wav","DE","Cleft"  ],
  ["20","filler","A","6","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","Cleft"  ],
  ["20","filler","A","9","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","Cleft"  ],
  ["20","filler","A","3","2","400","400","bottom-right","","","20_Only_False.PNG","Only Peter has a burger. ","20_DE.wav","DE","Cleft"  ],
  ["21","filler","A","9","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","Cleft"  ],
  ["21","filler","A","3","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","Cleft"  ],
  ["21","filler","A","6","2","400","400","bottom-right","","","21_Only_False.PNG","Only Tina has a black cat. ","21_DE.wav","DE","Cleft"  ],
  ["22","filler","A","3","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","Cleft"  ],
  ["22","filler","A","6","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","Cleft"  ],
  ["22","filler","A","9","2","400","400","bottom-right","","","22_Only_False.PNG","Only Corinna has a lion. ","22_DE.wav","DE","Cleft"  ],
  ["23","filler","A","6","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","Cleft"  ],
  ["23","filler","A","9","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","Cleft"  ],
  ["23","filler","A","3","2","400","400","top-right","","","23_Only_False.PNG","Only Samuel has a blue book. ","23_DE.wav","DE","Cleft"  ],
  ["24","filler","A","9","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","Cleft"  ],
  ["24","filler","A","3","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","Cleft"  ],
  ["24","filler","A","6","2","400","400","bottom-right","","","24_Only_False.PNG","Only Sönke has a cow. ","24_DE.wav","DE","Cleft"  ],
  ["25","filler","B","3","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","Cleft"  ],
  ["25","filler","B","6","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","Cleft"  ],
  ["25","filler","B","9","2","400","400","bottom-left","","","25_Only_True.PNG","Only Lisa has a red bag. ","25_DE.wav","DE","Cleft"  ],
  ["26","filler","B","6","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","Cleft"  ],
  ["26","filler","B","9","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","Cleft"  ],
  ["26","filler","B","3","2","400","400","top-right","","","26_Only_True.PNG","Only Anthea has a green pen. ","26_DE.wav","DE","Cleft"  ],
  ["27","filler","B","9","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","Cleft"  ],
  ["27","filler","B","3","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","Cleft"  ],
  ["27","filler","B","6","2","400","400","top-left","","","27_Only_True.PNG","Only Susanne has a red flower. ","27_DE.wav","DE","Cleft"  ],
  ["28","filler","B","3","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","Cleft"  ],
  ["28","filler","B","6","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","Cleft"  ],
  ["28","filler","B","9","2","400","400","bottom-right","","","28_Only_True.PNG","Only Hermine has a tomato. ","28_DE.wav","DE","Cleft"  ],
  ["29","filler","B","6","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","Cleft"  ],
  ["29","filler","B","9","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","Cleft"  ],
  ["29","filler","B","3","2","400","400","top-right","","","29_Only_True.PNG","Only Jacob has green rubber boots. ","29_DE.wav","DE","Cleft"  ],
  ["30","filler","B","9","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","Cleft"  ],
  ["30","filler","C","3","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","Cleft"  ],
  ["30","filler","C","6","2","400","400","bottom-left","","","30_Only_True.PNG","Only Alina has a blue shovel. ","30_DE.wav","DE","Cleft"  ],
  ["31","filler","C","3","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","Cleft"  ],
  ["31","filler","C","6","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","Cleft"  ],
  ["31","filler","C","9","2","400","400","top-right","","","31_False.PNG","Sarah has a rabbit. ","31_DE.wav","DE","Cleft"  ],
  ["32","filler","C","6","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","Cleft"  ],
  ["32","filler","C","9","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","Cleft"  ],
  ["32","filler","C","3","2","400","400","top-right","","","32_False.PNG","Markus has a mouse. ","32_DE.wav","DE","Cleft"  ],
  ["33","filler","C","9","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","Cleft"  ],
  ["33","filler","C","3","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","Cleft"  ],
  ["33","filler","C","6","2","400","400","bottom-left","","","33_False.PNG","Tanja has a sheep. ","33_DE.wav","DE","Cleft"  ],
  ["34","filler","C","3","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","Cleft"  ],
  ["34","filler","C","6","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","Cleft"  ],
  ["34","filler","C","9","2","400","400","top-right","","","34_False.PNG","Daniel has a bicycle. ","34_DE.wav","DE","Cleft"  ],
  ["35","filler","C","6","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","Cleft"  ],
  ["35","filler","C","9","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","Cleft"  ],
  ["35","filler","C","3","2","400","400","top-left","","","35_False.PNG","Silas has a teddy. ","35_DE.wav","DE","Cleft"  ],
  ["36","filler","C","9","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","Cleft"  ],
  ["36","filler","C","3","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","Cleft"  ],
  ["36","filler","C","6","2","400","400","top-right","","","36_False.PNG","Magda has an ice-cream. ","36_DE.wav","DE","Cleft"  ]
];